# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-31 16:21:55
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Analysis Tools.tbx")
    water_bodies_Fribourg_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\water_bodies_Fribourg.shp"
    wetlands_Fribourg_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\wetlands_Fribourg.shp"
    streets_Fribourg_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\streets_Fribourg.shp"
    rivers_fribourg_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\rivers_fribourg.shp"

    # Process: Multiple Ring Buffer (Multiple Ring Buffer) (analysis)
    water_bodies_Fribourg_MultipleRingBuffer2_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\Final_proj_spatial_analysis\\water_bodies_Fribourg_MultipleRingBuffer3.shp"
    arcpy.analysis.MultipleRingBuffer(Input_Features=water_bodies_Fribourg_shp, Output_Feature_class=water_bodies_Fribourg_MultipleRingBuffer2_shp, Distances=[150, 300, 500], Buffer_Unit="Meters", Field_Name="distance", Dissolve_Option="ALL", Outside_Polygons_Only="FULL", Method="PLANAR")

    # Process: Add Field (Add Field) (management)
    water_bodies_Fribourg_MultipleRingBuffer2_shp_2_ = arcpy.management.AddField(in_table=water_bodies_Fribourg_MultipleRingBuffer2_shp, field_name="cost", field_type="FLOAT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) (management)
    water_bodies_Fribourg_MultipleRingBuffer3_shp = arcpy.management.CalculateField(in_table=water_bodies_Fribourg_MultipleRingBuffer2_shp_2_, field="cost", expression="costCalc(float(!distance!))", expression_type="PYTHON3", code_block="""def costCalc(distance):
   if distance == 250:
       return -0.33
   elif distance == 100:
       return -0.66
   else:
       return -1
    """, field_type="LONG", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Multiple Ring Buffer (2) (Multiple Ring Buffer) (analysis)
    wetlands_Fribourg_MultipleRingBuffer2_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\Final_proj_spatial_analysis\\wetlands_Fribourg_MultipleRingBuffer3.shp"
    arcpy.analysis.MultipleRingBuffer(Input_Features=wetlands_Fribourg_shp, Output_Feature_class=wetlands_Fribourg_MultipleRingBuffer2_shp, Distances=[0, 300, 600, 1000], Buffer_Unit="Meters", Field_Name="distance", Dissolve_Option="ALL", Outside_Polygons_Only="FULL", Method="PLANAR")

    # Process: Add Field (2) (Add Field) (management)
    wetlands_Fribourg_MultipleRingBuffer2_shp_2_ = arcpy.management.AddField(in_table=wetlands_Fribourg_MultipleRingBuffer2_shp, field_name="cost", field_type="LONG", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (2) (Calculate Field) (management)
    wetlands_Fribourg_MultipleRingBuffer3_shp = arcpy.management.CalculateField(in_table=wetlands_Fribourg_MultipleRingBuffer2_shp_2_, field="cost", expression="costCalc2(float(!distance!))", expression_type="PYTHON3", code_block="""def costCalc2(distance):
   if distance == 1000:
       return -0.33
   elif distance == 600:
       return -0.66
   else:
       return -1
    """, field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Multiple Ring Buffer (3) (Multiple Ring Buffer) (analysis)
    streets_Fribourg_MultipleRingBuffer2_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\Final_proj_spatial_analysis\\streets_Fribourg_MultipleRingBuffer3.shp"
    arcpy.analysis.MultipleRingBuffer(Input_Features=streets_Fribourg_shp, Output_Feature_class=streets_Fribourg_MultipleRingBuffer2_shp, Distances=[5, 100, 150], Buffer_Unit="Meters", Field_Name="distance", Dissolve_Option="ALL", Outside_Polygons_Only="FULL", Method="PLANAR")

    # Process: Add Field (4) (Add Field) (management)
    streets_Fribourg_MultipleRingBuffer2_shp_2_ = arcpy.management.AddField(in_table=streets_Fribourg_MultipleRingBuffer2_shp, field_name="cost", field_type="LONG", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (3) (Calculate Field) (management)
    streets_Fribourg_MultipleRingBuffer3_shp = arcpy.management.CalculateField(in_table=streets_Fribourg_MultipleRingBuffer2_shp_2_, field="cost", expression="costCalc3(float(!distance!))", expression_type="PYTHON3", code_block="""def costCalc3(distance):
   if distance == 5:
       return 2
   elif distance == 50:
       return 1
   else:
       return 0.5
    """, field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Multiple Ring Buffer (5) (Multiple Ring Buffer) (analysis)
    rivers_fribourg_MultipleRingBuffer2_shp = "C:\\Users\\dhett\\Documents\\data_science_master\\SDASM\\Final_assignment\\Final_proj_spatial_analysis\\rivers_fribourg_MultipleRingBuffer3.shp"
    arcpy.analysis.MultipleRingBuffer(Input_Features=rivers_fribourg_shp, Output_Feature_class=rivers_fribourg_MultipleRingBuffer2_shp, Distances=[5, 60, 250], Buffer_Unit="Meters", Field_Name="distance", Dissolve_Option="ALL", Outside_Polygons_Only="FULL", Method="PLANAR")

    # Process: Add Field (3) (Add Field) (management)
    rivers_fribourg_MultipleRingBuffer2_shp_2_ = arcpy.management.AddField(in_table=rivers_fribourg_MultipleRingBuffer2_shp, field_name="cost", field_type="LONG", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (4) (Calculate Field) (management)
    rivers_fribourg_MultipleRingBuffer3_shp = arcpy.management.CalculateField(in_table=rivers_fribourg_MultipleRingBuffer2_shp_2_, field="cost", expression="costCalc4(float(!distance!))", expression_type="PYTHON3", code_block="""def costCalc4(distance):
   if distance == 5:
       return 1
   elif distance == 50:
       return -1
   elif distance == 100:
       return 0.66
   else:
       return 0.33
    """, field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\dhett\Documents\data_science_master\SDASM\Final_assignment\Final_proj_spatial_analysis\Final_proj_spatial_analysis.gdb", workspace=r"C:\Users\dhett\Documents\data_science_master\SDASM\Final_assignment\Final_proj_spatial_analysis\Final_proj_spatial_analysis.gdb"):
        Model()
